In [ ]:
#1
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#2
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#or
import numpy as np
a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#3
import numpy as np
a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4
import random
a=np.random.randint(0,1,10)
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#5
a=np.zeros(10)
b=np.ones(10)
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#6
a=np.array([10,20,30,40,50])
print(a[2])

30


In [ ]:
#7
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
print(a[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
7


In [ ]:
#8
a=np.array([5,10,15,20,25])
print(a[4])

25


In [ ]:
#9
a=np.array([1,3,5,7,9,11])
print(a[1])
print(a[3])
print(a[4])

3
7
9


In [ ]:
#or
a=np.array([1,3,5,7,9,11])
selected_elements=a[[1,2,4]]
print(selected_elements)

[3 5 9]


In [ ]:
#10
a=np.array([[[1,2],[3,4]],[[5,6],[7,8,]]])
print(a)
print(a.shape)
print(a[1,1,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
8


In [ ]:
#11
a=np.array([2,4,6,8,10,12])
print(a[:3])

[2 4 6]


In [ ]:
#12
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[:2])
print(a[:,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 3  4]
 [ 7  8]
 [11 12]]


In [ ]:
#change
import numpy as np
a= np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(a[:2,-2:])

[[3 4]
 [7 8]]


In [ ]:
#13
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a[0::2])

[0 2 4 6 8]


In [ ]:
#14
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[:,2:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]]


In [ ]:
#15
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
b=a[1:4,1:4]
print(b)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
#16
a=np.arange(6)
b=a.astype(float)
print(b)

[0. 1. 2. 3. 4. 5.]


In [ ]:
#17
a=np.array([[True,False,True],[False,True,False],[True,True,False]])
print(a)

[[ True False  True]
 [False  True False]
 [ True  True False]]


In [ ]:
#18
a=np.array([1+2j,3+4j,5+6j])
print(a)

[1.+2.j 3.+4.j 5.+6.j]


In [ ]:
#19
a=np.array(["1","2","3"])
b=a.astype(int)
print(b)

[1 2 3]


In [ ]:
#20
a=np.array([1.1,2.1,3.1,4.1])
b=a.astype(int)
print(a)
print(b)

[1.1 2.1 3.1 4.1]
[1 2 3 4]


NUMPY PRACTICE QUESTION -  2

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
b=a.copy()
a[2]=6
print(a)
print(b)

[1 2 6 4 5]
[1 2 3 4 5]


In [4]:
import numpy as np
y=a.view()
y[2]=6
print(a)
print(y)

[1 2 6 4 5]
[1 2 6 4 5]
